// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8eRvoGP3ENBvVi7DImsdjUgQkcya8j10',
    appId: '1:444622149452:web:3699feaba7218f52dee1e9',
    messagingSenderId: '444622149452',
    projectId: 'tendaku-d88f0',
    authDomain: 'tendaku-d88f0.firebaseapp.com',
    storageBucket: 'tendaku-d88f0.appspot.com',
    measurementId: 'G-S1PMVZ00FN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfqmoRZBpRtgc2UHWnLOGgPHNiokAommI',
    appId: '1:444622149452:android:e2c5ba80ce461961dee1e9',
    messagingSenderId: '444622149452',
    projectId: 'tendaku-d88f0',
    storageBucket: 'tendaku-d88f0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqIyY4Ozx5_xyr-qIK0d8xpYiIIRrp45c',
    appId: '1:444622149452:ios:2446106deb0acb6adee1e9',
    messagingSenderId: '444622149452',
    projectId: 'tendaku-d88f0',
    storageBucket: 'tendaku-d88f0.appspot.com',
    iosBundleId: 'com.example.tendakuApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqIyY4Ozx5_xyr-qIK0d8xpYiIIRrp45c',
    appId: '1:444622149452:ios:512b1bb3e2ee55b4dee1e9',
    messagingSenderId: '444622149452',
    projectId: 'tendaku-d88f0',
    storageBucket: 'tendaku-d88f0.appspot.com',
    iosBundleId: 'com.example.tendakuApp.RunnerTests',
  );
}
